import fs from 'node:fs';
const json = (file, change) => { const data=JSON.parse(fs.readFileSync(file,'utf8').replace(/^\uFEFF/,''));change(data);fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n'); };
const edit = (file, before, after) => { let data=fs.readFileSync(file,'utf8');if(!data.includes(before))throw new Error('Missing edit: '+file+' '+before.slice(0,60));fs.writeFileSync(file,data.replace(before,after)); };
json('shared/survival.json',s=>{s.dayDuration=180;s.nightDuration=90;});
json('shared/shelter.json',s=>{s.deposit={x:6,z:6.8,width:1.4,depth:1.1,height:2.25,range:2.8};});
json('shared/zombies.json',s=>{s.types.normal.speed=1.65;s.types.fast.speed=2.65;s.types.tank.speed=1.15;s.types.guardian.speed=1.45;});
edit('client/src/domain/config.ts','hp: 100, speed: 4','hp: 100, speed: 5.2');
edit('client/src/world/ShelterLayout.ts','export const SHELTER_CORE_ID = "shelter-core";','export const SHELTER_CORE_ID = "shelter-core";\nexport const SHELTER_DEPOSIT = layout.deposit;\nexport const SHELTER_DEPOSIT_ID = "shelter-deposit";');
edit('client/src/world/WorldLayout.ts','SHELTER_WALLS, SHELTER_CORE }','SHELTER_WALLS, SHELTER_CORE, SHELTER_DEPOSIT }');
edit('client/src/world/WorldLayout.ts','...BASE_WALLS, ...SHELTER_WALLS, SHELTER_CORE,','...BASE_WALLS, ...SHELTER_WALLS, SHELTER_CORE, SHELTER_DEPOSIT,');
edit('client/src/world/World.ts','SHELTER_CORE_ID, inBase }','SHELTER_CORE_ID, SHELTER_DEPOSIT, SHELTER_DEPOSIT_ID, inBase }');
edit('client/src/world/World.ts','this.buildShelter();',`this.buildShelter();
    const depot = SHELTER_DEPOSIT;
    const cabinet = this.box('resource-deposit-cabinet',depot.width,depot.height,depot.depth,depot.x,depot.height/2,depot.z,surfaceMaterial(scene,'metal'),true);
    cabinet.metadata={depositId:SHELTER_DEPOSIT_ID};
    const depotDoor=this.box('resource-deposit-door',depot.width-.14,depot.height-.18,.07,depot.x,depot.height/2,depot.z-depot.depth/2-.035,this.trim);
    depotDoor.isPickable=true;depotDoor.metadata={depositId:SHELTER_DEPOSIT_ID};
    const handle=this.box('resource-deposit-handle',.08,.55,.12,depot.x+.43,1.3,depot.z-depot.depth/2-.1,this.gold);
    handle.isPickable=true;handle.metadata={depositId:SHELTER_DEPOSIT_ID};
    this.box('resource-deposit-light',.45,.1,.08,depot.x,1.94,depot.z-depot.depth/2-.07,this.material('deposit-light','#a2cfb1','#6ca787'));
    if(typeof document!=='undefined'){
      const label=new DynamicTexture('deposit-sign',{width:256,height:128},scene,false);label.drawText('DEPOSIT',null,73,'bold 35px sans-serif','#e6e1c8','#263d34');
      const mat=this.material('deposit-label','#ffffff');mat.diffuseTexture=label;
      const sign=this.box('deposit-label',1,.35,.03,depot.x,.75,depot.z-depot.depth/2-.08,mat);sign.isPickable=true;sign.metadata={depositId:SHELTER_DEPOSIT_ID};
    }`);
edit('client/src/player/CombatTarget.ts','data?.buildingId ?? null','data?.buildingId ?? data?.depositId ?? null');
edit('client/src/domain/Simulation.ts','inHall, inBase, SHELTER_CORE_ID }','inHall, inBase, SHELTER_CORE_ID, SHELTER_DEPOSIT, SHELTER_DEPOSIT_ID }');
edit('client/src/domain/Simulation.ts','    this.depositResources();\r\n','');
edit('client/src/domain/Simulation.ts',"if (this.phase !== 'playing' || !inBase(this.player.position)) return deposited;","if (this.phase !== 'playing' || !inHall(this.player.position) || distance(this.player.position, SHELTER_DEPOSIT) > SHELTER_DEPOSIT.range || !hasLineOfSight(this.player.position, SHELTER_DEPOSIT, this.obstacles)) return deposited;");
edit('client/src/domain/Simulation.ts','  drainEvents(): GameEvent[]',`  interact(targetId: string | null): string {
    if(targetId!==SHELTER_DEPOSIT_ID)return 'Podejdź do skrzyni DEPOSIT w Shelterze i naciśnij E';
    const deposited=this.depositResources();
    return deposited.wood||deposited.iron ? 'Zdeponowano materiały' : this.carried.wood||this.carried.iron ? 'Magazyn pełny albo punkt depozytu poza zasięgiem' : 'Plecak jest pusty';
  }
  drainEvents(): GameEvent[]`);
edit('client/src/domain/Simulation.ts',"|| !inBase(this.player.position) || this.cycle.state.period !== 'day') return 'Rozwijaj umiejętności za dnia w Shelterze';", ") return 'Rozwijaj umiejętności podczas runu';");
edit('client/src/ui/SkillPanel.ts',"import { inBase } from '../world/ShelterLayout';\r\n",'');
edit('client/src/ui/SkillPanel.ts',"const allowed = inBase(sim.player.position) && sim.cycle.state.period === 'day';","const allowed = ['playing','paused'].includes(sim.phase);");
edit('client/src/core/InputManager.ts','  onSkillToggle:', '  onInteract: () => void = () => {};\n  onSkillToggle:');
edit('client/src/core/InputManager.ts',"'KeyN', 'KeyF',","'KeyN', 'KeyF', 'KeyE',");
edit('client/src/core/InputManager.ts',"if (event.code === 'KeyF' && !event.repeat)","if (event.code === 'KeyE' && !event.repeat) this.onInteract();\n      if (event.code === 'KeyF' && !event.repeat)");
edit('client/src/core/Game.ts','    this.input.onSkillToggle =',"    this.input.onInteract = () => this.hud.notify(this.simulation.interact(combatTarget(this.scenes.scene,this.controller.camera,3)));\n    this.input.onSkillToggle =");
edit('client/src/ui/Hud.ts','SHELTER_CORE_ID }','SHELTER_CORE_ID, SHELTER_DEPOSIT_ID }');
edit('client/src/ui/Hud.ts','<span class="curse-icon" aria-hidden="true">☠</span><div class="corruption-gauge"><label>SKAŻENIE <b id="corruption-value">0%</b></label>',`<span class="psyche-icon" aria-hidden="true"><svg viewBox="0 0 36 40"><path d="M11 37v-9C4 24 4 15 7 9 10 2 21 1 27 7c4 4 5 8 4 13l3 5h-6v6H18v6" fill="none" stroke="currentColor" stroke-width="2.5"/><path d="M12 12c-3-5 6-7 7-3 5-5 11 2 6 5 5 4 0 9-4 6-2 5-8 2-7-2-5 0-5-6-2-6Zm6-3v14m-7-8h14" fill="none" stroke="currentColor" stroke-width="1.5"/></svg></span><div class="corruption-gauge" role="progressbar" aria-label="Psyche"><label class="sr-only"><b id="corruption-value">100%</b></label>`);
edit('client/src/ui/Hud.ts','aria-label="Skażenie i zasoby przy sobie"','aria-label="Psyche i zasoby przy sobie"');
edit('client/src/ui/Hud.ts','const corruption = Math.ceil(sim.corruption.value);','const corruption = Math.ceil(sim.corruption.value);\n    const psyche=100-corruption;\n    this.nodes[\'corruption-fill\'].closest(\'[role="progressbar"]\')?.setAttribute(\'aria-valuenow\',String(psyche));');
edit('client/src/ui/Hud.ts',"textContent = corruption + '%';","textContent = psyche + '%';");
edit('client/src/ui/Hud.ts',"style.width = corruption + '%';","style.width = psyche + '%';");
edit('client/src/ui/Hud.ts','!(resource || coreTarget)','!(resource || coreTarget || targetId===SHELTER_DEPOSIT_ID)');
edit('client/src/ui/Hud.ts','    if (coreTarget) this.nodes',"    if(targetId===SHELTER_DEPOSIT_ID)this.nodes['interaction'].innerHTML='<kbd>E</kbd> DEPOSIT · oddaj Wood / Iron do Shelteru';\n    if (coreTarget) this.nodes");
edit('client/src/ui/Hud.ts','Powrót na teren Shelteru automatycznie odkłada materiały do magazynu.','E przy urządzeniu DEPOSIT wewnątrz Shelteru oddaje materiały do magazynu.');
edit('client/src/core/Game.ts','Skażenie rani ·','Psyche wyczerpane ·');
fs.appendFileSync('client/src/style.css',`\n.psyche-icon{width:34px;height:38px;display:block;color:#d4d9c8}.psyche-icon svg{width:100%;height:100%}.sr-only{position:absolute!important;width:1px!important;height:1px!important;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap}.corruption-gauge .bar{height:12px;margin-top:0}.corruption-gauge .bar i{background:linear-gradient(90deg,#b48258,#b8c394)}\n`);
